languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://victor-sw.github.io/resume/"
title = "Example - CV"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#555"
colorPageBackground = "#ddd"
colorPrimary = "#1DA1F2DD"
colorSecondary = "#1DA1F280"
colorIconPrimary = "#fff"
colorIconBackground = "#1DA1F2DD"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#555"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#1DA1F2A0"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = true
